"""empty message

Revision ID: 4bc4d24ae00
Revises: None
Create Date: 2015-02-22 23:49:42.831890

"""

# revision identifiers, used by Alembic.
revision = '4bc4d24ae00'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_name'), 'point', ['name'], unique=True)
    op.create_table('powerline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('powerline')
    op.drop_index(op.f('ix_point_name'), table_name='point')
    op.drop_table('point')
    ### end Alembic commands ###
